---
# Source: kubedb-catalog/templates/elasticsearch-psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: elasticsearch-db
  labels:
    chart: "kubedb-catalog-0.11.0"
    app: "kubedb-catalog"
    release: "kubedb-operator"
    heritage: "Tiller"
spec:
  privileged: true  #Allowing privileged pods is necessary for ES db only!
  allowPrivilegeEscalation: true #Allowing privilege escalation is necessary for ES db only!
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  allowedCapabilities:
  - IPC_LOCK
  - SYS_RESOURCE

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: elasticsearch-snapshot
  labels:
    chart: "kubedb-catalog-0.11.0"
    app: "kubedb-catalog"
    release: "kubedb-operator"
    heritage: "Tiller"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny

