---
# Source: kubedb-catalog/templates/redis-psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: redis-db
  labels:
    chart: "kubedb-catalog-0.11.0"
    app: "kubedb-catalog"
    release: "kubedb-operator"
    heritage: "Tiller"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny

