apiVersion: v1
kind: Pod
metadata:
  name: demo-flask-pod-9
  namespace: demo9
  labels:
    app: demo-flask-pod-9
spec:
  containers:
    - name: test-container
      image: sekharkaredla/flask-mysql-basic:trytwo
      env:
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-demo-instance-secret
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-demo-instance-secret
            key: password
      - name: MYSQL_HOST
        valueFrom:
          secretKeyRef:
            name: mysql-demo-instance-secret
            key: host