apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mysql-demo-instance
  namespace: demo10
  labels:
    app: demo-flask-pod-mysql-10
spec:
  clusterServiceClassExternalName: mysql
  clusterServicePlanExternalName: mysql
  parameters:
    metadata:
      labels:
        app: demo-app-pod-mysql-instance-10
    spec:
      version: "8.0-v1"
      storageType: Ephemeral
      terminationPolicy: WipeOut