---
# Source: kubedb/templates/service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedb-operator
  namespace: kube-system
  labels:
    chart: "kubedb-0.11.0"
    app: "kubedb"
    release: "kubedb-operator"
    heritage: "Tiller"


