---
# Source: service-broker/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-service-broker
  labels:
    chart: "service-broker-0.3.1"
    app: "service-broker"
    release: "release-name"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-service-broker
subjects:
  - kind: ServiceAccount
    name: release-name-service-broker
    namespace: default

