---
# Source: service-broker/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-service-broker
  labels:
    chart: "service-broker-0.3.1"
    app: "service-broker"
    release: "release-name"
    heritage: "Tiller"
rules:
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - appbindings
  verbs: ["get"]
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  verbs: ["list"]
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - clusterservicebrokers
  verbs: ["delete"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["list"]
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get"]
- apiGroups:
  - kubedb.com
  resources:
  - mysqls
  - postgreses
  - elasticsearches
  - mongodbs
  - memcacheds
  - redises
  verbs: ["get", "list", "create", "delete"]

