---
# Source: service-broker/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appscode-service-broker
  namespace: kube-system
  labels:
    chart: "service-broker-0.3.1"
    app: "service-broker"
    release: "appscode-service-broker"
    heritage: "Tiller"

