---
# Source: service-broker/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-service-broker
  namespace: default
  labels:
    chart: "service-broker-0.3.1"
    app: "service-broker"
    release: "release-name"
    heritage: "Tiller"

